#SELECT * FROM tabloadi (en basit, buradaki * bütün kolonlar demek)
#SELECT kolon1 FROM tabloadi (sadece kolon1)
#SELECT kolon2 FROM tabloadi LIMIT 1 (sadece 1 satır aldık fakar baştan 1)
#SELECT kolon1 FROM tabloadi LIMIT 5 OFFSET 1 (burada 1 satır atladıktan sonra 5 satır çek dedik)
#SELECT isim, soyisim FROM uyeler WHERE isim = 'furkan' (ismi sadece furkan olanları çektik)
#SELECT isim, soyisim FROM uyeler WHERE isim = 'furkan' AND soyisim='d' (ismi furkan, soyadı d olanları çektik)
#SELECT isim, soyisim FROM uyeler WHERE yas > 20 (yaşı 20'den büyük olanları çektik)
#tek satır çekmek için fetchone()
#tüm satırlar için fetchall()
